apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-wallet
  namespace: argocd
  labels:
    purpose: wallet
spec:
  destination:
    namespace: dome-wallet
    server: https://kubernetes.default.svc
  project: default
  source:
    path: ionos/dome-wallet/vault
    repoURL: https://github.com/in2workspace/dome-wallet-gitops
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
