apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: wallet-data
  name: wallet-data
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: wallet-data
      app.kubernetes.io/name: wallet-data
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: wallet-data
        app.kubernetes.io/name: wallet-data
    spec:
      containers:
      - name: wallet-data
        image: in2kizuna/wallet-data:v2.0.0
        imagePullPolicy: Always
        env:
        # Logging Configuration
        - name: LOGGING_LEVEL_ES_IN2_WALLETUSERREGISTRY
          value: "DEBUG"
        # OpenAPI Configuration
        - name: OPENAPI_SERVER_URL
          value: "https://dome-wallet.eu/wallet-data"
        - name: OPENAPI_SERVER_DESCRIPTION
          value: "Blockchain Connector Test Server"
        - name: OPENAPI_INFO_TITLE
          value: "Blockchain Connector"
        - name: OPENAPI_INFO_DESCRIPTION
          value: "Blockchain Connector Component"
        - name: OPENAPI_INFO_VERSION
          value: "2.0.0"
        - name: OPENAPI_INFO_TERMS_OF_SERVICE
          value: "https://example.com/terms"
        - name: OPENAPI_INFO_LICENSE_NAME
          value: "Apache 2.0"
        - name: OPENAPI_INFO_LICENSE_URL
          value: "https://www.apache.org/licenses/LICENSE-2.0.html"
        - name: OPENAPI_INFO_CONTACT_NAME
          value: "IN2, Ingeniería de la Información"
        - name: OPENAPI_INFO_CONTACT_URL
          value: "https://in2.es"
        - name: OPENAPI_INFO_CONTACT_EMAIL
          value: "contacto@in2.es"
        # Wallet Router Configuration
        - name: BROKER_DOMAIN
          value: "http://scorpio:9090"
        - name: BROKER_URL
          value: "/ngsi-ld/v1/entities"
        - name: WALLET-CRYPTO_DOMAIN
          value: "http://wallet-crypto:8080"
        - name: WALLET-CRYPTO_URL
          value: "/api/v2/secrets"
        - name: WALLET-WDA_DOMAIN
          value: "http://wallet-driving-application:8080"
