apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dome-wallet
spec:
  acme:
    email: said.ibrihen@orange.com
    privateKeySecretRef:
      name: letsencrypt-dome-wallet-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
          class: nginx
