ingress-nginx:
  fullnameOverride: ingress-nginx
  controller:
    replicaCount: 2
    service:
      loadBalancerIP: 85.215.150.150
      annotations:
        cloud.ionos.com/node-selector: nodepool=ingress
    nodeSelector:
      nodepool: ingress
    kind: DaemonSet
    config:
      large-client-header-buffers: "8 128k"
      http2-max-field-size: "32k"
      http2-max-header-size: "128k"
