---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wallet-server-secret
  namespace: dome-wallet
spec:
  encryptedData:
    HASHICORP_VAULT_TOKEN: "AgAiPhS1uSQ879Owuao0k69PmZ4Mdld+TdYcoNVMYDmJHgPI3x3CY3FtepyT5nRQ5jAjM05cP4cK2qbrqHPeCqPmXcX07PhQVzccPfkBX+BFZhulp1BcQaNBWFJG/nmi+i1kjKgoQPLzLpW9fuPteJbHez4Y4m1k2t6CU70sPzW72u7xuzvth836Z47opSwSHzD3vfmEfh/j6kXVY+Xk5NzhMEyaZW30IH1CbXcYvI34QIoC5KsPa4+3fa+K4/qe4wrynguZjwlndxUGGNynb8SAgGk5Aql9cfhHOzgulqkPZS4CZvEdSWkjzDlgaX3DGcHSqRjizW+MVeqghO2MVkcZwA+uDr6lJXPRKkuxYyr4N3+e6vuVL8yXNFbAugevTol0vCABsHXzgwpkCkRxH+MF7+NvYDs73xg3pP6LUauYhhAy5xteyY8hizP5MCwssNcvhBgCT9iwxh1Hzo71R8SuKrS1/tJvpm1Sc6FQ3XfSpNySt55+/OcsmrxMspImW1ceJq5CWbGl+5Hk7vNiu7/00MBymlF9zVfuiCoK2s0SSdXTGUkMekXR7FDMmXd5qxNid5sGiZEew44hRju8DKPN5lGvlWEuiZMOSoi5wKxNBxDY7gXnNvalmjOpmXbgjkL9BXwzNBTVZfXPUaC+cZdLP9turBG1VZnQKBVerbTcbe/bGtfOd2DJzCm0fO0xXaXGkBqIC/6AIl9x9Qx7m34NaBn0gqJXbgvqOvhkKw"
    EBSI_TEST_CLIENT_SECRET: "AgAh/5XwSceXminWTXFHQS6sr5dqR5Vjxfvsndl4aTkORzz6gOKTV6YcKWB/jCXaMpdJFDmUoh+pqFWYJ7JrV/CiPJSmB+/q9S1ze3yQRUEUud1yAHq5xkaKyyIYP+M/acgVPQj/8nwmhNgtdkwoMaMVsndX1wTcyazxDHRY7OXUFWgha64zlP0sCX/65fJdSPDBar5mZC/VBCKTiCgwy1nAGYM3aD0Cm4FfO0UZCHUR2OfAQsfMxfYBgIHKEhpN/VKKxYNYlwhagO5Y2f7dGPwXzNy02RYJiW6sukFbz1FJHpKTCHkyvTS2Hs7neXZBbUpSBIWxiFOUGOpl+8FmzWwD4rMIxCDLrZLzxxdrkVmRPO5Gnrt+oRY4VzuRFToJDFujsWe9vCddj8/eM7yUGGBptnm/qh2MXJAsohII53fMC+xQuINVQfb/3TLpH0VAgd+POabuorhN4UwbY7Cj7vrosMlDUYAMuJ3bNRmnnDD99q8HN4PUqTpaDgwSSPTXZJhbjnZX1dX+x/9f0Uc8Kvc25YwUwbOueGgktIZaJy43fGAGvwpPUVSRyb3np9dDydZI3W9/SmvEL/guTyvb121l+CTjgYUuJUtJVveM+Wniy+Pu/TbiICas63qSZBn3vHgsqbPCr341AwxIQ9eDK4FpyhQLj53XSvQFGdprTtqRFOiR5X3x4kp0Jd9wPgjGbDwGg3H3Y0yWj9hAYC1jDi8tpKh25ZZYTiNvjoMcs3//odQ"
  template:
    metadata:
      name: wallet-server-secret
      namespace: dome-wallet
