---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: wallet-server-secret
  namespace: dome-wallet
spec:
  encryptedData:
    HASHICORP_VAULT_TOKEN: AgADr6yLYWLw6DulS+V0rSqxxMVCVF2g6RAQfYuaV/0Fdg82+ayMRoKuCmFA8OR+hq1KDZxDAVOBS4a6eIsxMzn9H5QwlbGFuExEc9fbbGbNLGNkMyPyUcFcrfYf5Xv6a4eZqQYCpWTX+5x6RledwuHpPrvjW7I/TVtTBfK2uadIbdQS17LFQi2CdwUkCJvafLe7Y4MqPSOcH74Gm7ic8VD5XUpKgYpqyU/d3v+Hptx9iPgiRTjDkMBRhLzZ5IxRh+cE0BqeMn6LMXVxvosTYNP89aYB8Oi2JnXmHewqW7F2warlUY0WLUmAZKJMI4ivzm3HErQeQAheffkqGlq8xQlDFPicb3jhlCNnEUpW9cJEp9KGtW/V6YhCwTd1lO92264dRG5CsXjCrUg+pfAjahuSZpLf5+XW8E5ZV9byEdVl5QW9bYecqgXNWArFZD9VD261zLF1w3iRxwyj1DFt4F4M5nEtkyR3tSyImcbh6howKRzRUZlZTdFktSyzlgOWkjvAsfSrc4Ndxw2zR7KoSIdBskGKry4LAS2UkZ6LzS4VZV9rke/nnik8Db69vcwSHNdM+QFqmYYp+YiOSm7YxTmezdG9kQmTbuRr1/lTMdPSDyQX7d9kUDOt1DgcUkdSaVgNsDcxOqWgTuQ3VKxdkbjHFDi6mD07rtprl9XnGcTepPAAX0eb1+sgrWm+RsukVYeKcBKfs+XJsxPF9h6Wrnwk4S9w+zvb9qGStw5p4w==
    IDENTITY_PROVIDER_CLIENT_SECRET: AgADW3VaEwfY2aSy2EkcJ3QQWJSEt6alOwA/NXDKxgxaXcZxnkndJcPV2GCHAHjZBGzgpRiZFfTPqZt0VbErJi3j8FikUAM5NRfVLJ+oFwyYotEMPwX4X51huveUZEL+jSnxie8HY76EAieIz8Mg8ATqcWN+3xVgUaGS3bCta/8UE/P5uPNMsduEPgFCWZdFQ3CTeLyI03Z/ru/QZguMy1TO0PFJ1SKFKWq88aehvnr2Yw0VTNy233omIJh/jiiKaA7X3BnFkugB83SsosrtyDW2Qe73Ig1bqB8Xl2uFdMhI5tbyPj3O0bnn1Ns6ze82GIGYhwuTlV7ohSQh38NSbkDJucJvhqyRVJ8nq4hkZhfuV1MTNz7XibVHn+hdO0f39SAUH7OfBRSW4u34USbacDPHl4QcjyHqOp1qoRXNMiCFJWH7+J62jjzpyvXFUYoiQi1LxPZsN4ijnvEfNSg6qa+PhcdsWTLkN0cSM0M+wCuBHo8YM52WylsVkGRN67ZcCXf/KGXrT1i1iITYu1q99dl7nf1SpqOTMlgXnSjExdYX8dJeihTl+FnDigD69tVmd9fG6QpgUbZPGXp0INUjaZLnDFb9bgmmG2C7LInaup1GK7dYwDzldXPtjmUHFQblnhnoHjDIIZWasQ+ZH6re+qrF09VRi8zIYkAHmAWK1il7LybTJysumeriyZARsh5kwicsjaZPeqnzEod9ZiXJEljDjHKwhlYEh6JwKGxR9e0DiGY=
  template:
    metadata:
      name: wallet-server-secret
      namespace: dome-wallet
