apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: dome-wallet
spec:
  encryptedData:
    keycloak-admin: AgAO7OeSs+TObiDNrvX7REleQBuOyrFDjk0r02TNdOwnr8hMDq/fKDorsKyntUTuPSa8oCJQwQgxQw8hsQbejqy9AQmf95aHujOvWiwS7sOHeBW64sPbOP0KIFxCE7Tt1L3dP6nvcq/72Z4R6eavdZVYMX5IcF5l32TS1H9yKaHH+CnZMJCBFOkXQgkxsk5yB2YPZVokd45YLdCDnVOayFmEJbblIljQBRfetqGUFh7wyNzVIHEUYd7QO83573vnvJVdLrX0+tx7Rluwv8Z64Q/SuzZV50Q0sXhQhpOzYrWPlOjkGYCETP4YP9ua0KR46WmQGY4mYaTeUZ97LkwDZJv7O+9X0VqnkaJG98hKWnjRwcb/bRqj6Z6F57R7i+hTmr8ecfG993kIwQz1CDTXR5BrEWAiDf1vhsJ0ZT8v6JyNouM5kXGSoOdKiZZ2WnH7O/ktfgfMmXk3tx158DjijsmRQzlRqIpdE2MQXdlEXrKXTTcQC0e2jc+tv2dP79voOqHvbGAqyHtdsE2d9ywKob7oJTmVaHpG7Zg8wrh3/OkjxtCfGwax/2eQN3ih3tm0LNnuTRvgaAbdGcfaiajR2JUPu+X7TlMxGk+0Aw4GmuHTZuECNeTnseY+qx7diTk7JqMgwhPxtdvfdxUdWEkLSkBimXftOlBQLZhnNuJXDPObA2qVOvhhqSmEKDp3oiD9OcabEreUNl2VH/fsUZ+ckH23TGabXHsS
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: dome-wallet
    type: Opaque

